### ISSUE TITLE
2.0.2 Gerber archive doesn't contain internal layers

### ISSUE THREAD

**Issue by reykada** [PatrickBaus/SCAN2000#6]
I just realized it after 2-layer PCBs ordered and arrived when I started to assembly, luckily only FPGA and few capacitors were soldered only.

**Comment by PatrickBaus** [comment]
Oh, you are absolutely right. I am so sorry. I have added the missing layers to the CI and will release a new version immediately.

**Comment by reykada** [comment]
No worries, I had to check it myself before order PCBs. Thank you for the quick fix!

**Comment by PatrickBaus** [comment]
I have published version 2.0.3. As soon as the CI has built the files it should be available.

**Comment by reykada** [comment]
Cool, thanks for sharing the project!
